apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: group-specific-pods
spec:
  podSelector:
    matchLabels:
      group: database
  ingress:
  - from:
    - podSelector:
        matchLabels:
          group: webserver